# Change these first
owner: hernad
repo: upptime

sites:
  - name: www.bring.out.ba
    url: http://www.bring.out.ba
  - name: download bring.out.ba
    url: http://download.bring.out.ba/host.txt
  - name: next.cloud.out.ba
    url: https://next.cloud.out.ba/s/NPAyfsYPeStzDTN/download
  - name: redmine.bring.out.ba
    url: https://redmine.bring.out.ba/
  - name: bring.out odoo
    url: https://bringout.odoo.cloud.out.ba/
  - name: keycloak.bring.out.ba
    url: https://keycloak.cloud.out.ba/
  - name: headscale
    url: https://headscale.out.ba/nonexistent-test-endpoint
  - name: dns paris
    url: pub3.out.ba
    check: "tcp-ping"
    port: 53
  - name: dns frankfurt
    url: pub1.out.ba
    check: "tcp-ping"
    port: 53 

#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bring.out.ba
  # baseUrl: /your-repo-name
  logoUrl: https://www.bring-out-ba.uk/bring_cakija.png
  name: Upptime bring.out
  introTitle: "Status bring.out servisa"
  introMessage: Statusna stranica servisa bring.out doo Sarajevo u **realnom vremenu**. Izvor [GitHub repozitorij](https://github.com/hernad/upptime). Server nije potreban - samo GitHub Actions, Issues, and Pages.  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# aktivirane akcije, dodan branch gh-pages
# GH_PAT secret, prije toga definisan token https://upptime.js.org/docs/get-started/